### ISSUE TITLE
Install on Debian 12 Bookworm?

### ISSUE THREAD

**Issue by ComputerSmiths** [marcelblijleven/goodwe#59]
Bookworm is different, just to keep us on our toes:
> pip3 install goodwe
error: externally-managed-environment
[... use apt install python3-xyz ...]

> apt install python3-goodwe
E: Unable to locate package python3-goodwe

Is there some other incantation I should be using?   Can I install it from the directory I 'git clone'ed?

Thanks!

**Comment by d-k-bo** [comment]
That's not an issue caused by this library. It is a feature of `pip` to prevent breaking your global python environment. You should use e.g. [`venv`](https://docs.python.org/3/library/venv.html) to create a virtual environment. See also https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/.
